import { SimplePool } from "nostr-tools";

export const RELAYS = [
  "wss://relay.damus.io",
  "wss://nos.lol",
  "wss://relay.snort.social",
  "wss://nostr-pub.wellorder.net",
  "wss://nostr.wine/",
  // "wss://nostr.zebedee.cloud",
  // "wss://relay.nostr.band",
  "wss://puravida.nostr.land",
  "wss://nostr.milou.lol",
  // "wss://brb.io",
  "wss://nostr.mutinywallet.com",
  // "wss://nostr.bitcoiner.social",
  "wss://atlas.nostr.land",
  "wss://purplepag.es",
  "wss://nostr.oxtr.dev",
  "wss://welcome.nostr.wine",
  // "wss://relay.nostr.bg",
  "wss://relayable.org",
  // "wss://relay.nostr.info",
  "wss://nostr.mom",
  "wss://nostr.plebchain.org",
  // "wss://nostr.orangepill.dev",
  "wss://relay.bitblockboom.com",
  "wss://relay.nostriches.org",
  "wss://relay.nostrplebs.com",
  "wss://relay.nostrgraph.net",
  "wss://relay.plebstr.com",
  // "wss://bitcoiner.social",
  // "wss://nostr-pub.semisol.dev",
  "wss://no.str.cr",
  "wss://relay.nostrati.com",
  "wss://universe.nostrich.land",
  // "wss://nostr-01.bolt.observer",
  "wss://nostr.uselessshit.co",
  "wss://relay.nostrich.land",
  // "wss://nostr-relay.untethr.me",
  // "wss://nostr.onsats.org",
  // "wss://nostr.delo.software",
  // "ws://umbrel:4848",
  // "wss://nostr.zerofeerouting.com",
  "wss://nostr.massmux.com",
  // "wss://nostr-2.zebedee.cloud",
  "wss://nostr.inosta.cc",
  // "ws://monad.jb55.com:8080",
  // "wss://nostr-relay.wlvs.space",
  // "wss://feeds.nostr.band/meme",
  // "wss://nostr.openchain.fr",
  // "wss://nostr.v0l.io",
  // "wss://relay.stoner.com",
  "wss://relay.nostr.com.au",
  // "wss://nostr.walletofsatoshi.com",
  "wss://nostr.slothy.win",
  // "wss://expensive-relay.fiatjaf.com",
  "wss://rsslay.nostr.net",
  // "wss://nostr.drss.io",
  // "wss://relayer.fiatjaf.com",
  // "wss://nostr1.tunnelsats.com",
  "wss://relay.f7z.io",
  // "wss://relay.nostrica.com",
  // "wss://nostr.bongbong.com.au",
  "wss://rsslay.nostr.moe",
  "wss://relay.utxo.one",
  "wss://nostr.einundzwanzig.space",
  "wss://nostr.swiss-enigma.ch",
  "wss://nostr-relay.derekross.me",
  // "wss://relay.nostr.pro",
  "wss://sg.qemura.xyz",
  // "wss://feeds.nostr.band/popular",
  "wss://relay.punkhub.me",
  "wss://lightningrelay.com",
  "wss://nostr.ownscale.org",
  "wss://relay.austrich.net",
  // "wss://relay.nostr.band/all",
  // "wss://nostr.sandwich.farm",
  "wss://rly.nostrkid.com",
  "wss://relay.mostr.pub",
  "wss://e.nos.lol",
  // "wss://nostr.relayer.se",
  // "wss://relay.nostr.ch",
  "wss://nostr.lu.ke",
  "wss://relay.wellorder.net",
  // "wss://feeds.nostr.band/pics",
  "wss://nostr-verif.slothy.win",
  "wss://nostr-verified.wellorder.net",
  // "wss://public.nostr.swissrouting.com",
  // "wss://nostr.gives.africa",
  // "wss://relay.kronkltd.net",
  // "wss://nostr.chaker.net",
  // "wss://rsslay.fiatjaf.com",
  // "wss://relay.grunch.dev",
];

export const POOL = new SimplePool();
