import type { Metadata } from "next";

import Sidebar from "./components/Sidebar";
import Header from "./components/header/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "resolvr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html 

      className="h-full bg-gray-900 dark">
      <body className="h-full bg-gray-700/10">
        <Sidebar />
        <Header />
        {children}
      </body>
    </html>
  );
}
